name: 'Terraform Plan'
description: 'Terraform Custom Workflow'

on:
  workflow_call:
        inputs:
        STATEBUCKET:
          description: 'statebucket name'
          required: true
          default: mybucksoham-cicd 
        ENVIRONMENT:
           description: 'environment name'
           required: true
           default: test
        REGION:
           description: 'region'
           required: true
           default: ap-south-1
 runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ inputs.STATEBUCKETNAME }}" -backend-config="region=${{ inputs.REGION }}"
    - name: Terraform Plan
      run: terraform plan
