name: 'Terraform Plan'
description: 'Terraform Custom Workflow'

inputs:
  STATEBUCKET:
    description: 'statebucket name'
    required: true  
  ENVIRONMENT:
     description: 'environment name'
     required: true
  REGION:
     description: 'region'
     required: true
 runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ inputs.STATEBUCKETNAME }}" -backend-config="region=${{ inputs.REGION }}"
    - name: Terraform Plan
      run: terraform plan
