name: 'Terraform Plan'
description: 'Terraform Custom Workflow'

inputs:
  STATEBUCKET:
    description: 'statebucket name'
    required: true
    options:
    - bucketname
  ENVIRONMENT:
     description: 'environment name'
     required: true
     options:
      - environmentname

env:
  STATEBUCKETNAME: ${{ github.event.inputs.STATEBUCKET }}
  ENVIRONMENTNAME: ${{ github.event.inputs.ENVIRONMENT }}
runs:
  using: "composite"
  steps:
    - name: terraform Initiation
      run: terraform init -backend-config="bucket=${STATEBUCKET}"
    - name: terraform plannning
      run: terraform plan
