name: "Reusable workflow 1"

on: 
  workflow_call:

jobs:


   ru2-job1:
     runs-on: ubuntu-latest

     steps:


      - uses: actions/checkout@v3

      - name: val-task

        run: |
          echo "I am user"























# name: 'Terraform Plan'
# description: 'Terraform Custom Workflow'

# inputs:
#   STATEBUCKET:
#     description: 'statebucket name'
#     required: true

# runs:
#   using: "composite"
#   steps:
#     - name: terraform init
#       run: terraform init
#     - name: terraform plan
#       run: terraform plan
